#!/bin/bash
# Bash script to package the current *.py scripts into a sengle *.pyz executable
# and then push to the (current) remote git repo
# It optionally takes a remote commuit label as an argument
# James Turner 31/8/21

# Create a single folder executable (run existing script)
./createSingleFileExecutable

# Extract the supplied first argument (if supplied) to be used as a commit label
commitLabel='"'${1:-"Commit changes to remote"}'"'
echo "Using $commitLabel"
# git commit changes with a default label (Windows test....") if none supplied, or else the supplied label
git commit -am "$commitLabel"

# push to remote repo
git push
