#!/bin/bash
# This utility script takes turns __main__.py into a single executable python file containing all dependencies
##### Zip up __main__.py first (into studiocontroller.pyz)
# Specify the script where main() (the entry point of the program where main() lives)
# zipapp will create an output file with this name and a .pyz file extension
zipappMainScript="studiocontroller"

# Declare dependencies as an array
dependencies=(
	requests==2.24.0
	terminaltables==3.1.0
	validator_collection==1.4.2
  RouterOS-api=0.17.0
	)


# Temporary folder where pip will collect the dependencies. The name of this folder will determine the name of the file executable archive
targetSubFolder="tempDownloadsFolder"

echo "Creating $zipappMainScript.pyz executable archive file"
# echo ${dependencies[@]}

echo "Use proxy www-cache.reith.bbc.co.uk:80?"
read answer
if [ "$answer" != "${answer#[Yy]}" ] ;then
	python3 -m pip --proxy www-cache.reith.bbc.co.uk:80 install  "${dependencies[@]}" --target $targetSubFolder
else
    python3 -m pip install  "${dependencies[@]}" --target $targetSubFolder
fi


echo "downloading dependancies into new subfolder $targetSubFolder"
# python3 -m pip --proxy www-cache.reith.bbc.co.uk:80 install  ${dependencies[@]} --target $targetSubFolder
# python3 -m pip install  ${dependencies[@]} --target $targetSubFolder

echo 'Copying *.py (program code) and html folder into target subfolder $targetSubFolder for parcelling up with dependencies'
cp -r *.py html *.ico build_tools scripts templates $targetSubFolder

echo "Creating $targetSubFolder.pyz file from contents of $targetSubFolder" 
python3 -m zipapp $targetSubFolder -c -p "/usr/bin/env python" -m "$zipappMainScript:main" -o "$zipappMainScript.pyz"

 echo "Deleting $targetSubFolder subfolder (as no longer required)"
 rm -rf $targetSubFolder
